services:
  otel:
    image: docker.io/grafana/otel-lgtm:0.7.6
    ports:
      - 3000:3000
      - 4317:4317
      - 4318:4318
    volumes:
      - ./container/data/grafana:/data/grafana
      - ./container/data/prometheus:/data/prometheus
      - ./container/conf/grafana/provisioning:/otel-lgtm/grafana/conf/provisioning
      - ./container/var/dashboards:/var/dashboards
    environment:
      - GF_PATHS_DATA=/data/grafana