services:
  nginx:
    image: nginx:1.27
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ./container/html:/usr/share/nginx/html:ro
      - ./container/conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./container/conf/nginx/40-generate-cert.sh:/docker-entrypoint.d/40-generate-cert.sh:ro
  otel:
    image: docker.io/grafana/otel-lgtm:0.7.6
    ports:
      - 3000:3000
      - 4317:4317
      - 4318:4318
    volumes:
      - ./container/data/grafana:/data/grafana
      - ./container/data/prometheus:/data/prometheus
      - ./container/conf/grafana/provisioning:/otel-lgtm/grafana/conf/provisioning
      - ./container/var/dashboards:/var/dashboards
    environment:
      - GF_PATHS_DATA=/data/grafana