services:
  otel:
    image: docker.io/grafana/otel-lgtm:0.7.6
    ports:
      - 3000:3000
      - 4317:4317
      - 4318:4318
    volumes:
      - $PWD/container/grafana:/data/grafana
      - $PWD/container/prometheus:/data/prometheus
      - $PWD/container/loki:/loki
    environment:
      - GF_PATHS_DATA=/data/grafana